# PostgreSQL (production)
spring.datasource.url=jdbc:postgresql://localhost:5432/shopflowdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=shopflow
spring.datasource.password=shopflow_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
